### ISSUE TITLE
Incorrect FSF addresses in mli header files

### ISSUE THREAD

**Issue by TC01** [ocsigen/lwt_log#1]
Hi,

I know this library is deprecated, but current lambda-term ([1.13](https://opam.ocaml.org/packages/lambda-term/lambda-term.1.13/)) depends on it, so I'm looking at providing a Fedora package.

It seems that the FSF address is incorrect in the MLI header files, e.g. from [lwt_log.mli](https://github.com/ocsigen/lwt_log/blob/master/src/unix/lwt_log.mli):

```
  * You should have received a copy of the GNU Lesser General Public
  * License along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
  * 02111-1307, USA.
```

The right address is:

>  Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

I wrote [a patch](https://tc01.fedorapeople.org/ocaml/lwt/lwt-log-fsf-address.patch) fixing this. I can open a pull request if you want.

**Comment by aantron** [comment]
Thanks, I'll be happy to merge such a PR!
